# Generated by Django 2.1.7 on 2021-03-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdata',
            name='positionType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RawData.PositionType'),
        ),
    ]
